[project]
name = "mathu"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "anthropic>=0.45.2",
    "httpx>=0.28.1",
    "openai>=1.61.1",
    "python-dotenv>=1.0.1",
    "requests>=2.32.3",
]
